title: Raise Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://raisestatus.netlify.app
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: true
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#FF5630"
  systems:
    - name: Web App
      description: The MyRaise, Web Editor, Dashboard, Follow Up & Birthdays and
        Stewardship pages.
      category: Uncategorized
      link: https://example.com/
    - name: First Drafts
      description: All automated and manually requested First Drafts, including any
        which are received in the morning.
      category: Uncategorized
    - name: Data Loads
      description: This is the service responsible for loading in data from your CRM
        to Raise.
      category: Uncategorized
    - name: Writebacks
      category: Uncategorized
      description: This is the service responsible for returning data from Raise to
        your CRM.
    - name: Email Integration
      category: Uncategorized
      description: This is the service responsible for picking up any emails you send
        as actions and returning the data to Raise. This service is reliant on a
        third-party provider.
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#ffffff"
  enableLastMod: true
  headerTextColor: white
  logo: /img/1_raise-tagline.svg
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#FFAB00"
  notice: "#00B8D9"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#36B37E"
  categories:
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: true
