title: Raise Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://raisestatus.netlify.app
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: true
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#FF5630"
  systems:
    - name: MyRaise
      category: Web App
      description: ""
    - name: Web Editor
      category: Web App
    - name: Dashboard
      category: Web App
    - name: UUID Pages
      category: Web App
      description: Follow Ups & Birthdays and Stewardships pages - accessed via the Guide
    - name: Automated First Drafts
      description: First Drafts sent out automatically in the morning
      category: First Drafts
    - name: Manual First Drafts
      category: First Drafts
      description: First Drafts requested manually from the Guide, Dashboard or UUID pages
    - name: Rapid Fire
      category: First Drafts
      description: First Draft prompts sent automatically after taking an action on a
        previous prompt
    - name: Data Loads - Salesforce and RE NXT
      description: Loading data from your CRM to Raise
      category: CRM Integrations
    - name: Data Loads - All Other CRMs
      description: Loading data from your CRM to Raise
      category: CRM Integrations
    - name: Writebacks - Salesforce and RE NXT
      category: CRM Integrations
      description: Returning data from Raise to your CRM
    - name: Writebacks - All Other CRMs
      description: Returning data from Raise to your CRM
      category: CRM Integrations
    - name: Email Integration
      category: Third Party Integrations
      description: ""
    - name: FTP Site
      category: Third Party Integrations
      description: ""
    - name: Email Servers
      category: Third Party Integrations
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#ffffff"
  enableLastMod: true
  headerTextColor: white
  logo: /img/1_raise-tagline.svg
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#FFAB00"
  notice: "#00B8D9"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#36B37E"
  categories:
    - name: Uncategorized
      untitled: true
      closed: false
    - name: First Drafts
    - name: Web App
      description: ""
      closed: true
    - name: CRM Integrations
      closed: true
    - name: Third Party Integrations
      closed: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: true
